### ISSUE TITLE
renaming folders doesn't work

### ISSUE THREAD

**Issue by jadeqwang** [mnutt/davros#10]
When I create a folder locally in my Davros/OwnCloud folder (on my Mac), it temporarily creates a folder called "untitled folder," which, by the time I've typed in the folder name I intend to call it, creates an error and is unable to sync with my Davros grain (which already knows about "untitled folder").

My current workaround is to create a folder elsewhere (e.g., on my desktop), make sure it's named correctly, and drag/drop it into my Davros/OwnCloud folder. When I do that, it works fine. :)

**Comment by mnutt** [comment]
Hmm, are you selective syncing and not syncing the grain's "untitled folder" to your local machine? I was trying to reproduce, and if I already have an "untitled folder" in the directory I'm sharing, choosing _New Folder_ automatically creates "untitled folder 2". (I'm on Yosemite 10.10.5)

Oddly though, I get a Sandstorm stack trace when it tries to sync the rename from "untitled folder 2" to anything else, which may be what you're seeing as well. I'll try to look into why that's happening later tonight.

```
app/server/pre-meteor.js:424
    var hostname = req.headers.host.split(":")[0];
                                    ^
TypeError: Cannot call method 'split' of undefined
    at dispatchToMeteorOrStaticPublishing (app/server/pre-meteor.js:424:37)
    at Server.redirectToMeteorOrServeStaticPublishing (app/server/pre-meteor.js:414:12)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2113:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socket.ondata (http.js:1971:22)
    at TCP.onread (net.js:528:27)
```

**Comment by jadeqwang** [comment]
Hey @mnutt , I'm also on Yosemite 10.10.5 (though you can probably tell from my default background in this screen recording): 

https://youtu.be/BuDLTgzj0jk

I'm not doing any selective syncing that I'm aware of...

And here's the log from the ownCloud client:
![image](https://cloud.githubusercontent.com/assets/1584904/11199459/a3339b4c-8c82-11e5-8fe3-49af722ae66a.png)

And the Sandstorm debug log:

![image](https://cloud.githubusercontent.com/assets/1584904/11199560/52e612fe-8c83-11e5-9976-01b82bfd94f3.png)

I hope this helps repro!

**Comment by mnutt** [comment]
Thanks, that looks like exactly the same error I'm seeing on my side. I'll take a look.

**Comment by mnutt** [comment]
Ok, I think I got it: https://github.com/sandstorm-io/sandstorm/pull/1171

**Comment by mnutt** [comment]
I think this should work now, feel free to reopen if it's still causing problems.

**Comment by ovizii** [comment]
Just for the record: had the same problem too.
Created a local folder on my MAC inside the Davros sync folder but by the time I had typed its new name, Davros had already created an "untitled folder" on sandstorm and printed this error: http://screencast.com/t/ZzR2IYkQaBD5

**Comment by jadeqwang** [comment]
Just yesterday, I encountered the same problem again. :(

**Comment by mnutt** [comment]
Hmm, this time I'm having trouble replicating. I'm on Sandstorm 0.135 and Davros 0.14.1; are you using the same versions? Would you mind pasting the log from the ownCloud client again?

**Comment by ovizii** [comment]
Sandstorm: v0.135 
Davros: 0.14.1 

Looks fixed on my side now, created a folder, took my time naming it and Davros seems ot have picked it up properly:

'''13.12.2015 12:11:55 untitled folder                                                 ownCloud                      Moved to Test            
13.12.2015 12:11:49 untitled folder                                                 ownCloud                      Uploaded                 
'''
