### ISSUE TITLE
Wrong disk usage reported

### ISSUE THREAD

**Issue by mnutt** [mnutt/davros#2]
When syncing for the first time, davros reports the entire disk usage as preparing to sync. When you're expecting to sync 1MB of files and it tells you you're about to sync 3.7GB, that's unsettling to say the least.

Also, in at least one instance `df` is returning back a wonky value:

```
/opt/app/node_modules/jsDAV/lib/DAV/backends/fs/directory.js:224
                (statvfs.blocks - statvfs.bfree),// * statvfs.bsize,
                        ^

TypeError: Cannot read property 'blocks' of null
    at /opt/app/node_modules/jsDAV/lib/DAV/backends/fs/directory.js:224:25
    at /opt/app/server/dav/statvfs-shim.js:18:16
    at ChildProcess.exithandler (child_process.js:194:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: App exited with status code: 1
```

**Comment by mnutt** [comment]
The first issue is fixed in v0.10.7; the second one may need to wait until sandstorm exposes quotas.
